language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t spacefox42/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spacefox42/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-v2"
  env: "Dockerreactv2-env"
  bucket_name: "elasticbeanstalk-us-east-1-133678316947"
  bucket_path: "docker-react-v2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
